apps/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

apps/pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('', views.listar_pedidos, name='listar'),
    path('<int:pk>/', views.detalhar_pedido, name='detalhar'),
    path('criar/', views.criar_pedido, name= 'criar'),
    path('<int:pk>/editar/', views.editar_pedido, name='editar'),
    path('<int:pk>/deletar/', views.deletar_pedido, name='deletar'),
]

apps/produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'

urlpatterns = [
    path('', views.listar_produtos, name='listar'),
    path('<int:pk>/', views.detalhar_produto, name='detalhar'),
    path('criar/', views.criar_produto, name= 'criar'),
    path('<int:pk>/editar/', views.editar_produto, name='editar'),
    path('<int:pk>/deletar/', views.deletar_produto, name='deletar'),
]

apps/relatorios/urls.py
from django.urls import path
from . import views

app_name = 'relatorios'

urlpatterns = [
    path('', views.relatorios, name='relatorio'),
]

gestao_sabores/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('produtos/', include('apps.produtos.urls_produtos')),
    path('categoria/',include('apps.produtos.urls_categoria')),
    path('pedidos/',include('apps.pedidos.urls')),
    path('relatorios/', include('apps.relatorios.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="headerbase fixed-top">
        <nav>
            <img src="/static/images/logo.png" alt="logo aqui" class="nav-logo">

            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'categoria:listar' %}">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'produtos:listar' %}">Produtos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pedidos:listar' %}">Pedidos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'relatorios:relatorio' %}">Relatórios</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        {%block content%}
        {%endblock%}
    </main>
    <footer class="fixed-bottom text-white py-3" style="background-color:#49240a;">
        <div class="container-fluid">
            <div class="row align-items-center">
                <!-- Data e Hora -->
                <div class="col-md-6">
                    <div class="d-flex align-items-center">
                        <i class="bi bi-clock fs-5 me-2" style="color: #DEB887;"></i>
                        <div>
                            <div id="data-hora-rodape" class="fs-6"></div>
                            <small class="text-muted" style="color: #DEB887 !important;">
                                Fuso horário de Brasília-DF
                            </small>
                        </div>
                    </div>
                </div>
                
                <!-- Informações -->
                <div class="col-md-6 text-md-end">
                    <p class="mb-1">
                        <strong>SÁBORES | BOLOS E LANCHES</strong>
                    </p>
                    <p class="mb-0" style="color: #DEB887;">
                        © 2025 - v1.0 | Bodocó - PE
                    </p>
                </div>
            </div>
        </div>
    </footer>

    
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
     <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>